const data = {
	products: [
		{
			name: "nigeria shirt",
			slug: "nigeria-sssshirt-f",
			category: "shirt",
			image: "/images/nigeriatrouser.jpg",
			price: 40,
			brand: "senator",
			rating: 4.5,
			numReview: 8,
			countInStock: 10,
			description: "a popular nigeria shirt",
		},
		{
			name: "pant",
			slug: "pant-d",
			category: "gucci",
			image: "/images/gucciTrouser.jpeg",
			price: 50,
			brand: "nike",
			rating: 4.5,
			numReview: 8,
			countInStock: 20,
			description: "a gucci pant",
		},

		{
			name: "african trouser",
			slug: "african-trouser-c",
			category: "shirt",
			image: "/images/pastorTrouser.jpg",
			price: 70,
			brand: "nike",
			rating: 4.5,
			numReview: 8,
			countInStock: 20,
			description: "a popular trouser",
		},
		{
			name: "nigeria shirt",
			slug: "nigeria-shirt-b",
			category: "shirt",
			image: "/images/nigeriatrouser.jpg",
			price: 60,
			brand: "senator",
			rating: 4.5,
			numReview: 8,
			countInStock: 12,
			description: "a popular nigeria shirt",
		},
		{
			name: "african shirt",
			slug: "african-shirt-a",
			category: "shirt",
			image: "/images/africanshirt.jpg",
			price: 180,
			brand: "nike",
			rating: 4.5,
			numReview: 8,
			countInStock: 10,
			description: "a popular shirt",
		},
		{
			name: "nigeria senator shirt",
			slug: "african-shirt-v",
			category: "shirt",
			image: "/images/senatorshirt.jpg",
			price: 130,
			brand: "de-nuelx",
			rating: 4.5,
			numReview: 8,
			countInStock: 10,
			description: "a popular shirt",
		},
		{
			name: "combat-trouser",
			slug: "african-shirt-m",
			category: "shirt",
			image: "/images/ppp.jpeg",
			price: 80,
			brand: "nike",
			rating: 4.5,
			numReview: 8,
			countInStock: 10,
			description: "a popular shirt",
		},
	
	],
};
export default data;
